version: "3.8"
services:
  server:
    build: .
    container_name: ChatBoardServer
    restart: unless-stopped
    command: [ "/wait_for_it.sh", "java", "-jar", "ChatBoardServer.jar" ]
    network_mode: host
    volumes:
      - ./userdata:/userdata
      - ./logs:/logs
#      - ./migrate:/migration
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
#    volumes:
#      - ./postgres_data:/var/lib/postgresql/data
