version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - D:\Projekte\IntelliJ\ChatBoardServer_new\src\main\resources\:/data
    environment:
      - SLEEP_MINS=30