version: '3.8'
services:
  app:
    build: .
    command: [ "/wait_for_it.sh", "java", "-jar", "ChatBoardServer_new.jar" ]
    network_mode: host
    volumes:
      - /home/hades/ChatBoardServer/src/main/resources/userdata/:/userdata
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - /home/hades/ChatBoardServer/src/main/resources/init_db:/docker-entrypoint-initdb.d
      - /home/hades/postgres_data:/var/lib/postgresql/data