version: "3.8"
services:
  app:
    build: .
    container_name: ChatBoardServer
    restart: unless-stopped
    command: [ "/wait_for_it.sh", "java", "-jar", "ChatBoardServer_new.jar" ]
    network_mode: host
    volumes:
      - /home/hades/ChatBoardServer/userdata:/userdata
      - /home/hades/ChatBoardServer/logs:/logs
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - /home/hades/ChatBoardServer/init_db:/docker-entrypoint-initdb.d
      - /home/hades/ChatBoardServer/postgres_data:/var/lib/postgresql/data