version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /home/hades/ChatBoardServer/src/main/resources/userdata/:/userdata
    env_file:
      - .env

  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /home/hades/ChatBoardServer/src/main/resources/init_db:/docker-entrypoint-initdb.d
      - /home/hades/ChatBoardServer/src/main/resources/postgres_data:/var/lib/postgresql/data